services:
  web:
    container_name: static-web-server
    build:
      context: ../
      dockerfile: ./infra/nginx/Dockerfile.nginx
      target: vite-react-ts-example
    ports:
      - '8085:80'
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart:
      unless-stopped
